apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: 49d07d71fdd2f07ea90a6c6d67b054ee17895088441f9eed31b87e8e7fa7c0f6
  NEXTAUTH_SECRET: d+TeXQKeHVaT765J79c93a+RoOu1hRn/IVzUKXvrHHk=

